### ISSUE TITLE
Switch to unicode emojis

### ISSUE THREAD

**Issue by akc42** [akc42/football-mobile#21]
As I see it, the old emoticon system in previous versions of mobile is completely out of date.  It was hardly every used and its going to be a pain to implement it as is.  Instead we know have emoji, and particularly mobile phones and ipads have emojis available on them as standard.  So we should switch over.  which I think involves a number of steps
- [x]  #22 go through existing database and get a list of the actual emoticons that have been used
- [x]  #23 define a replacement emoji for all existing used emoticons
- [x] create an emoticonremoval branch for work below
- [x] remove emoticon references from server start up
- [x]  #29 make a conversion script (ideally in just sql, but alternatively as a special one off javascript program)
- [x] integrate conversion with server start
- [x] #32 tidy up code to remove old emoticon elements.

**Comment by akc42** [comment]
Note that integrating with server start is a non issue because the existing upgrade script can handle it.
