### ISSUE TITLE
Switch to images for teams

### ISSUE THREAD

**Issue by akc42** [akc42/football-mobile#24]
I think it is better (especially for caching) to store the team icons as static images.  

- [x] #25 go through existing images and turn them into png files stored in client/appimages/teams with just tid as their basename
- [x] #26 fix code in client to use image files rather than database data 
- [x] #31 fix api calls on server to remove returning logos
- [x] #30 fix database conversions to remove logos entirely (we will solely reference via tid)
